var youngsModulus="Young’s modulus, numerical constant, named for the 18th-century English physician and physicist Thomas Young, that describes the elastic properties of a solid undergoing tension or compression in only one direction, as in the case of a metal rod that after being stretched or compressed lengthwise returns to its original length. Young’s modulus is a measure of the ability of a material to withstand changes in length when under lengthwise tension or compression. Sometimes referred to as the modulus of elasticity, Young’s modulus is equal to the longitudinal stress divided by the strain. \nStress and strain may be described as follows in the case of a metal bar under tension.If a metal bar of cross-sectional area A is pulled by a force F at each end, the bar stretches from its original length L0 to a new length Ln. (Simultaneously the cross section decreases.) The stress is the quotient of the tensile force divided by the cross-sectional area, or F/A. The strain or relative deformation is the change in length, Ln − L0, divided by the original length, or (Ln − L0)/L0. (Strain is dimensionless.) Thus Young’s modulus may be expressed mathematically as Young’s modulus = stress/strain = (FL0)/A(Ln − L0)."
var pressure = "pressure, in the physical sciences, the perpendicular force per unit area, or the stress at a point within a confined fluid. The pressure exerted on a floor by a 42-pound box the bottom of which has an area of 84 square inches is equal to the force divided by the area over which it is exerted; i.e., it is one-half pound per square inch. The weight of the atmosphere pushing down on each unit area of Earth’s surface constitutes atmospheric pressure, which at sea level is about 15 pounds per square inch. In SI units, pressure is measured in pascals; one pascal equals one newton per square metre. Atmospheric pressure is close to 100,000 pascals."
var force = "A force is an action that changes or maintains the motion of a body or object. Simply stated, a force is a push or a pull. Forces can change an object’s speed, its direction, and even its shape. Pushing a door open, pulling it closed, stretching a rubber band—all of these actions require force.Force is a vector quantity—that is, it has both magnitude (size) and direction. Although forces cannot be seen directly, their effects can be observed and measured. Force is measured using a force meter. The unit of measurement for force is the newton, symbolized by the letter N and named in honor of the English physicist Isaac Newton. Much of what is known today about force is based on Newton’s three fundamental laws of motion."

var lessonList = []
lessonList.push(force)
lessonList.push(pressure)
lessonList.push(youngsModulus)

module.exports = lessonList